travis:
  secure:
    BINSTAR_TOKEN: yGYmOiRwZlpJXy9tRHK/C66CuFkZm6Vhim76qss74YtX5JG+nYpAxab+1CgtsY5BdSfFn/c9ef7TA13QiXiot7cFT+WWHwpE8sw4BBWyvJG0TICnKKeU1d0zW142RIEUSng6UishHf8wTPwEfExs1xkwt02KzpCYI9p7zSYKtuawWkEZ7zSnxwQKL75OfRiUuMGCQdCeJe5wkLkAEa336+QoCwOuslrnZOHiC1JVyWfcQRqFyQJwJ0WKgzsgBNZkUlHz1d/5mGwsAiXlFCdiXnqPGuS6wX2Ar8gO7JFp/v7OooqFZ8ySZr7zVPk+KJ0/YasfkiilTgL96FhhiqgNqk3ZMpEGmEhsVXIw0V+KZPFz2jvocqY7UNjsINjqPSIrFMkwspIqUb5c4ZE4K8i2G1yfkojyn6MR0xqRGT31wwx5KrZCHYKqBIrDk/6MbQ8qM8HMofkdZGKYJTQfB2bO5nUU79yq1X27Xsq8R+YJ+cjYH8jLmGiShXDVeGvMwl86WV6XjNu3QtfNN5JMS6LO2lzdvl8bFDnjgz23rTo+giZcQ0sGoj2sui9E/h19YLgRvC3pi34xjTJKXqW7/KfVsVvNS7TvOn5ddYB9EiYht5nEKdoQPIqv2XA1FwqwN0OCk53n/qniUJHXb1RaxJG1ISzLpi5JQQod+QE3CTczj2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
